CREATE DATABASE IF NOT EXISTS Painting;

USE Painting;

CREATE TABLE Episodes(
	[EpisodeID] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](50) NOT NULL,
	[EpisodeDate] [datetime] NULL
) ON [PRIMARY]

CREATE TABLE Subjects(
	[EPISODE] [nvarchar](50) NOT NULL,
	[TITLE] [nvarchar](50) NOT NULL,
	[APPLE_FRAME] [bit] NOT NULL,
	[AURORA_BOREALIS] [bit] NOT NULL,
	[BARN] [bit] NOT NULL,
	[BEACH] [bit] NOT NULL,
	[BOAT] [bit] NOT NULL,
	[BRIDGE] [bit] NOT NULL,
	[BUILDING] [bit] NOT NULL,
	[BUSHES] [bit] NOT NULL,
	[CABIN] [bit] NOT NULL,
	[CACTUS] [bit] NOT NULL,
	[CIRCLE_FRAME] [bit] NOT NULL,
	[CIRRUS] [bit] NOT NULL,
	[CLIFF] [bit] NOT NULL,
	[CLOUDS] [bit] NOT NULL,
	[CONIFER] [bit] NOT NULL,
	[CUMULUS] [bit] NOT NULL,
	[DECIDUOUS] [bit] NOT NULL,
	[DIANE_ANDRE] [bit] NOT NULL,
	[DOCK] [bit] NOT NULL,
	[DOUBLE_OVAL_FRAME] [bit] NOT NULL,
	[FARM] [tinyint] NOT NULL,
	[FENCE] [bit] NOT NULL,
	[FIRE] [bit] NOT NULL,
	[FLORIDA_FRAME] [bit] NOT NULL,
	[FLOWERS] [bit] NOT NULL,
	[FOG] [bit] NOT NULL,
	[FRAMED] [bit] NOT NULL,
	[GRASS] [bit] NOT NULL,
	[GUEST] [bit] NOT NULL,
	[HALF_CIRCLE_FRAME] [bit] NOT NULL,
	[HALF_OVAL_FRAME] [bit] NOT NULL,
	[HILLS] [bit] NOT NULL,
	[LAKE] [bit] NOT NULL,
	[LAKES] [tinyint] NOT NULL,
	[LIGHTHOUSE] [bit] NOT NULL,
	[MILL] [bit] NOT NULL,
	[MOON] [bit] NOT NULL,
	[MOUNTAIN] [bit] NOT NULL,
	[MOUNTAINS] [bit] NOT NULL,
	[NIGHT] [bit] NOT NULL,
	[OCEAN] [bit] NOT NULL,
	[OVAL_FRAME] [bit] NOT NULL,
	[PALM_TREES] [bit] NOT NULL,
	[PATH] [bit] NOT NULL,
	[PERSON] [bit] NOT NULL,
	[PORTRAIT] [bit] NOT NULL,
	[RECTANGLE_3D_FRAME] [bit] NOT NULL,
	[RECTANGULAR_FRAME] [bit] NOT NULL,
	[RIVER] [bit] NOT NULL,
	[ROCKS] [bit] NOT NULL,
	[SEASHELL_FRAME] [tinyint] NOT NULL,
	[SNOW] [bit] NOT NULL,
	[SNOWY_MOUNTAIN] [bit] NOT NULL,
	[SPLIT_FRAME] [tinyint] NOT NULL,
	[STEVE_ROSS] [bit] NOT NULL,
	[STRUCTURE] [bit] NOT NULL,
	[SUN] [bit] NOT NULL,
	[TOMB_FRAME] [bit] NOT NULL,
	[TREE] [bit] NOT NULL,
	[TREES] [bit] NOT NULL,
	[TRIPLE_FRAME] [bit] NOT NULL,
	[WATERFALL] [bit] NOT NULL,
	[WAVES] [bit] NOT NULL,
	[WINDMILL] [bit] NOT NULL,
	[WINDOW_FRAME] [tinyint] NOT NULL,
	[WINTER] [bit] NOT NULL,
	[WOOD_FRAMED] [tinyint] NOT NULL
) ON [PRIMARY]
    FOREIGN KEY (EpisodeID) REFERENCES Episodes(EpisodeID)
);

CREATE TABLE [dbo].[Colors](
	[ColorID] [smallint] IDENTITY(1,1) NOT NULL,
	[painting_index] [smallint] NOT NULL,
	[img_src] [nvarchar](100) NOT NULL,
	[painting_title] [nvarchar](50) NOT NULL,
	[season] [tinyint] NOT NULL,
	[episode] [tinyint] NOT NULL,
	[num_colors] [tinyint] NOT NULL,
	[youtube_src] [nvarchar](50) NOT NULL,
	[colors] [nvarchar](300) NOT NULL,
	[color_hex] [nvarchar](200) NOT NULL,
	[Black_Gesso] [bit] NOT NULL,
	[Bright_Red] [bit] NOT NULL,
	[Burnt_Umber] [bit] NOT NULL,
	[Cadmium_Yellow] [bit] NOT NULL,
	[Dark_Sienna] [bit] NOT NULL,
	[Indian_Red] [bit] NOT NULL,
	[Indian_Yellow] [bit] NOT NULL,
	[Liquid_Black] [bit] NOT NULL,
	[Liquid_Clear] [bit] NOT NULL,
	[Midnight_Black] [bit] NOT NULL,
	[Phthalo_Blue] [bit] NOT NULL,
	[Phthalo_Green] [bit] NOT NULL,
	[Prussian_Blue] [bit] NOT NULL,
	[Sap_Green] [bit] NOT NULL,
	[Titanium_White] [bit] NOT NULL,
	[Van_Dyke_Brown] [bit] NOT NULL,
	[Yellow_Ochre] [bit] NOT NULL,
	[Alizarin_Crimson] [bit] NOT NULL,
    FOREIGN KEY (EpisodeID) REFERENCES Episodes(EpisodeID)
);
