drop table if exists SubjectMatter;
drop table if exists SubjectMatter;
create table subjectmatter(
    IDRow Int Primary Key,
    EPISODE Text,
    TITLE Text,
    APPLE_FRAME Boolean,
    AURORA_BOREALIS Boolean,
    BARN Boolean,
    BEACH Boolean,
    BOAT Boolean,
    BRIDGE Boolean,
    BUILDING Boolean,
    BUSHES Boolean,
    CABIN Boolean,
    CACTUS Boolean,
    CIRCLE_FRAME Boolean,
    CIRRUS Boolean,
    CLIFF Boolean,
    CLOUDS Boolean,
    CONIFER Boolean,
    CUMULUS Boolean,
    DECIDUOUS Boolean,
    DIANE_ANDRE Boolean,
    DOCK Boolean,
    DOUBLE_OVAL_FRAME Boolean,
    FARM Boolean,
    FENCE Boolean,
    FIRE Boolean,
    FLORIDA_FRAME Boolean,
    FLOWERS Boolean,
    FOG Boolean,
    FRAMED Boolean,
    GRASS Boolean,
    GUEST Boolean,
    HALF_CIRCLE_FRAME Boolean,
    HALF_OVAL_FRAME Boolean,
    HILLS Boolean,
    LAKE Boolean,
    LAKES Boolean,
    LIGHTHOUSE Boolean,
    MILL Boolean,
    MOON Boolean,
    MOUNTAIN Boolean,
    MOUNTAINS Boolean,
    NIGHT Boolean,
    OCEAN Boolean,
    OVAL_FRAME Boolean,
    PALM_TREES Boolean,
    PATH Boolean,
    PERSON Boolean,
    PORTRAIT Boolean,
    RECTANGLE_3D_FRAME Boolean,
    RECTANGULAR_FRAME Boolean,
    RIVER Boolean,
    ROCKS Boolean,
    SEASHELL_FRAME Boolean,
    SNOW Boolean,
    SNOWY_MOUNTAIN Boolean,
    SPLIT_FRAME Boolean,
    STEVE_ROSS Boolean,
    STRUCTURE Boolean,
    SUN Boolean,
    TOMB_FRAME Boolean,
    TREE Boolean,
    TREES Boolean,
    TRIPLE_FRAME Boolean,
    WATERFALL Boolean,
    WAVES Boolean,
    WINDMILL Boolean,
    WINDOW_FRAME Boolean,
    WINTER Boolean,
    WOOD_FRAMED Boolean
);



COPY SubjectMatter(IDRow,EPISODE,TITLE,APPLE_FRAME,AURORA_BOREALIS,BARN,BEACH,BOAT,BRIDGE,BUILDING,BUSHES,CABIN,CACTUS,CIRCLE_FRAME,CIRRUS,CLIFF,CLOUDS,CONIFER,CUMULUS,DECIDUOUS,DIANE_ANDRE,DOCK,DOUBLE_OVAL_FRAME,FARM,FENCE,FIRE,FLORIDA_FRAME,FLOWERS,FOG,FRAMED,GRASS,GUEST,HALF_CIRCLE_FRAME,HALF_OVAL_FRAME,HILLS,LAKE,LAKES,LIGHTHOUSE,MILL,MOON,MOUNTAIN,MOUNTAINS,NIGHT,OCEAN,OVAL_FRAME,PALM_TREES,PATH,PERSON,PORTRAIT,RECTANGLE_3D_FRAME,RECTANGULAR_FRAME,RIVER,ROCKS,SEASHELL_FRAME,SNOW,SNOWY_MOUNTAIN,SPLIT_FRAME,STEVE_ROSS,STRUCTURE,SUN,TOMB_FRAME,TREE,TREES,TRIPLE_FRAME,WATERFALL,WAVES,WINDMILL,WINDOW_FRAME,WINTER,WOOD_FRAMED) 
FROM '/home/codeelisa/atlas-the-joy-of-painting-api/SubjectMatter.csv' 
DELIMITER ','
CSV
HEADER;

